USE task_manager;

CREATE TABLE IF NOT EXISTS `TASK` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IS_DONE` TINYINT NOT NULL DEFAULT 0,
  `DESCRIPTION` TEXT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = INNODB;